### ISSUE TITLE
cw-utils depends on cw2 and cw20 on cw-utils leads to recursive repo dependency

### ISSUE THREAD

**Issue by dzmitry-lahoda** [CosmWasm/cw-utils#12]
which is bad

**Comment by webmaster128** [comment]
cw2 is all about migrations by managing versions of the state. So I wonder it reasonable to just move [ensure_from_older_version](https://github.com/CosmWasm/cw-utils/blob/v1.0.2/src/migrate.rs#L5-L12) into cw2 too. It adds a semver dependency to cw2 but that's not too bad I guess.

WDYT @maurolacy @chipshort

**Comment by maurolacy** [comment]
Just checked and I don't see a problem with the current dependency tree: `cw-utils`, `cw20`, and the `cw20-base` contract all depend on `cw2`, directly or indirectly.

That said, I think it makes sense to move `ensure_from_older_version` from `cw-utils` to `cw2`. That, or move everything to a `cw-utils::version` mod, and get rid of `cw2`.

**Comment by webmaster128** [comment]
As far as I can see, it's a circle of repositories and not crates. This caused some maintenance annoyance in the past.
- cw-utils (cw-utils) -> cw2 (cw-plus) 
- cw20 (cw-plus) -> cw-utils (cw-utils)
 
means the repos cw-plus and cw-utils depend on each other.

> That, or move everything to a `cw-utils`' `version` (or `migrate`) module; and get rid of ugly `cw2` entirely.

I think at this point cw2 developed a bit of a brand and it makes more sense to clean it up than remove it. E.g. here we have a block explorer exposing CW2 version info:

<img width="854" alt="Bildschirmfoto 2023-11-13 um 10 12 20" src="https://github.com/CosmWasm/cw-utils/assets/2603011/d489e9ab-0bea-425c-9b1b-73d8c6076dd3">

https://neutron.celat.one/neutron-1/contracts/neutron16h2q0xyrnlwuu4kwj38qxjexlhf07ehhnk3c87l8srgn0uurm6dqq38jqy

**Comment by chipshort** [comment]
I agree that conceptually `ensure_from_older_version` belongs in `cw2`

**Comment by webmaster128** [comment]
Could one of you copy it over such that we can deprecate it in here?

**Comment by maurolacy** [comment]
> As far as I can see, it's a circle of repositories and not crates. This caused some maintenance annoyance in the past.

cw-utils (cw-utils) -> cw2 (cw-plus)
cw20 (cw-plus) -> cw-utils (cw-utils)
means the repos cw-plus and cw-utils depend on each other.

I see. This is basically because in the past everything was in a big `cw-plus` repo.

**Comment by maurolacy** [comment]
The best way to solve this circularity would be to move the `cw2` package to `cw-utils`. Which makes sense.

**Comment by webmaster128** [comment]
ensure_from_older_version is deprecated and will be removed in 2.0. This removes the dependency on cw2 from here. Closing in vavour of #20.
